# Building --------------------------------------------------------------------------------------------------------
[build-system]
requires = ["setuptools>=73.0.0", "wheel"]
build-backend = "setuptools.build_meta"

# Project settings ------------------------------------------------------------------------------------------------
[project]
name = "reco2gnizer"
version = "0.1.0"
description = "ReAct agent built with LangGraph, leveraging LLM reasoning and semantic web search to compute carbon footprints from product data."
readme = "README.md"
license = { text = "MIT" }
requires-python = "==3.14.4"

# Required dependencies -------------------------------------------------------------------------------------------
dependencies = [
    "langgraph==1.1.10",
    "langchain==1.2.17",
    "langchain-exa==1.1.0",
    "langchain-google-genai==4.2.2",
    "langchain-openai==1.2.1"
]

# Optional dependencies -------------------------------------------------------------------------------------------
[project.optional-dependencies]
dev = ["ruff==0.15.12", "pre-commit==4.6.0"]

# Other project settings ------------------------------------------------------------------------------------------
[project.urls]
"Source" = "https://github.com/michelepatella/reco2gnizer"

# Tools settings --------------------------------------------------------------------------------------------------
[tool.setuptools]
packages = ["reco2gnizer"]

[tool.setuptools.package-dir]
"reco2gnizer" = "src/reco2gnizer"

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["ALL"]
extend-select = ["D"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.pydocstyle]
convention = "google"
